### ISSUE TITLE
python csv read stdin until end

### ISSUE THREAD

**Issue by spotiris** [acfr/comma#64]
@andsok75 
Currently the python csv module does not support reading stdin until the end of the stream, but sys.stdin does support this. Presumably this is because there is no timeout or guarantee of a full packet via stdin.read(). An error is raised if it is attempted: "stdin requires positive size, got -1".

A workaround is below for the csv type point_t:
```
buf = stdin.read(-1)
num_packets = len(buf) // point_t.dtype.itemsize
print("got %d packets in %d bytes" % (num_packets, len(buf)), file=stderr)
points = np.fromstring(buf, dtype=point_t)
```
This could be included in to the csv module instead of raising the error.

**Comment by vlaskine** [comment]
@andsok75 : essentially, you would need to keep the same semantics as in comma c++ applications and make sure you reassemble the incoming packets, *not* just making sure that the whole stream is read; if in doubt, could we please talk first? also, this sounds to me as quite a high priority item, since we are very likely to start using python stuff in a realtime streaming context very soon (in july?)

**Comment by andsok75** [comment]
@spotiris : I've incorporated your workaround into the csv module. 

Incidentally, reading stdin until EOF is reached has always been supported in csv module. I think you just want to use stream.read(size=-1) to get all records from stdin in one go, rather than using stream.iter() to read chunks of some default number of records until EOF is reached. The latter method will read all data from stdin too, just not in one go. 

If I was reading data from a file, I would just specify source in the stream class to point to that file. 
Using stream(point_t, source=open('file','r')).read(-1) is more efficient than catting file into a script that uses stdin. I would only use the latter if the former was not possible or very inconvenient.

**Comment by spotiris** [comment]
Thanks Andrey, that's right - I want to avoid using an iterator because of
the overhead so I can process large batches of data quickly for some global
optimisation (that requires the whole data set).
Thanks
